### ISSUE TITLE
Test native plugins on iOS

### ISSUE THREAD

**Issue by emroussel** [emroussel/stockpile-app#218]
Barcode scanning and toast notifications seem to not work properly on Ionic View on iOS. We should figure out if it is a problem with Ionic View or with Stockpile.

**Comment by AdamVig** [comment]
Toast notifications work consistently and the barcode scanner did not have any freezing or crashing problems.

Possible bugs found while testing:
- inventory loads twice (could not reproduce, but if you encounter it, you'll know that it's not an isolated incident)
- screen is super jumpy when logging in - every time the keyboard changes state (when a field loses or gains focus), the screen jumps around until the keyboard loads fully
- extra space in "Item successfully edited" toast between "successfully" and "edited" (maybe)
- **the app creates items with empty barcodes**. When I tried to rent the created item, it said "Item does not exist," but I also could not create another item with the same barcode. The barcode was `0888670025116`, if that helps. It was successfully used to make the `GET` request for the item when attempting to rent it, so it seems like the barcode scanner worked correctly, but something after the scanner set the barcode to `undefined`.
- when creating a kit, setting the name wipes out any added items. Steps to reproduce:
  - create a kit
  - add one or more items to the kit
  - set the name of the kit
  - weird loading sequence, then all items previously added to the kit are removed and you have to start over
- when creating a kit, selecting the item fields to set them takes two taps: the first tap moves the label from its initial state to the top state, then the second tap actually opens the brand or model modal.
- when editing a kit, you can delete items from the kit with no confirmation. This is confusing because there is a save button that you would assume is necessary to press before any changes will be saved. The UI could cache any kit item deletions and then execute all the requests when the save button is pressed.

Things that could be improved (in my opinion):
- in inventory view, there is no indication of what filters are currently applied
- inventory view loads fresh every time I visit it, even when toggling back and forth between "Rental" and "Inventory." It should cache data and only refresh on demand (pull to refresh seems to be implemented)
- in inventory view, when either "Available" or "Rented" have no items, there should be a message that says "No items found" or something
- when adding an item by barcode, there is no warning that the item already exists until *after* you have filled out all the fields and hit "Save." It could save the user some time and frustration if this warning came as soon as the barcode was scanned instead of after they have entered data.
- show the value of the scanned barcode when creating or renting an item as a confirmation that something happened in the scan (maybe only useful for testing, but it does feel weird to scan and end up on a view that *implies* a successful scan, but does not explicitly show that the scan was successful)
- after deleting an item, you are taken back to the "view item" page. Should be dumped back on the inventory page with a refreshed list of items (that does not include the deleted item)

**Comment by emroussel** [comment]
It is weird that everything worked. Multiple people definitely encountered problems on their devices, so this will need more testing to make sure it is a problem with Ionic View and not the app.

@AdamVig regarding your comments:

> screen is super jumpy when logging in - every time the keyboard changes state (when a field loses or gains focus), the screen jumps around until the keyboard loads fully

I could not reproduce this on either the browser or Android, but opened #249

> extra space in "Item successfully edited" toast between "successfully" and "edited" (maybe)

Good catch, this is actually present in most of the messages. Will be fixed in #247 

> **the app creates items with empty barcodes**. When I tried to rent the created item, it said "Item does not exist," but I also could not create another item with the same barcode. The barcode was `0888670025116`, if that helps. It was successfully used to make the `GET` request for the item when attempting to rent it, so it seems like the barcode scanner worked correctly, but something after the scanner set the barcode to `undefined`.

Good catch, will be fixed in #248

> when creating a kit, setting the name wipes out any added items. Steps to reproduce:
> - create a kit
> - add one or more items to the kit
> - set the name of the kit
> - weird loading sequence, then all items previously added to the kit are removed and you have to start over

Opened #250, but was not able to reproduce on browser or Android. Can you add more details on how this happens?

> when creating a kit, selecting the item fields to set them takes two taps: the first tap moves the label from its initial state to the top state, then the second tap actually opens the brand or model modal.

This is actually a problem for all fields that open a modal. I meant to fix that a while ago, but forgot. Will do in #251 

> when editing a kit, you can delete items from the kit with no confirmation. This is confusing because there is a save button that you would assume is necessary to press before any changes will be saved. The UI could cache any kit item deletions and then execute all the requests when the save button is pressed.

This does not *actually* saves the changes unless you click save, but the view kit page seems to still update to what the edit kit page had. Opened #252 

> in inventory view, there is no indication of what filters are currently applied

Opened #253

> inventory view loads fresh every time I visit it, even when toggling back and forth between "Rental" and "Inventory." It should cache data and only refresh on demand (pull to refresh seems to be implemented)

This was done because there are a lot of operations that modify the inventory and instead of listening to all the possible events, I made the page reload every time it is focused. A pull to refresh is a good idea (right now, it's only an infinite scroll), but I feel like it might be confusing to not view the item you just created or modified.

> in inventory view, when either "Available" or "Rented" have no items, there should be a message that says "No items found" or something

Opened #254 

> when adding an item by barcode, there is no warning that the item already exists until *after* you have filled out all the fields and hit "Save." It could save the user some time and frustration if this warning came as soon as the barcode was scanned instead of after they have entered data.

Good idea -> #255

> show the value of the scanned barcode when creating or renting an item as a confirmation that something happened in the scan (maybe only useful for testing, but it does feel weird to scan and end up on a view that *implies* a successful scan, but does not explicitly show that the scan was successful)

Not sure if showing the value of the barcode is the most user friendly solution, but definitely a good idea. #256

> after deleting an item, you are taken back to the "view item" page. Should be dumped back on the inventory page with a refreshed list of items (that does not include the deleted item)

This was fixed yesterday in #239! I simply haven't published the changes on Ionic View yet.


Thanks for all the feedback, it's definitely useful.

**Comment by AdamVig** [comment]
I actually tested not in Ionic View, but in a native installation of the app (using `ionic run`). So, I think that might prove that Ionic View is the problem, but it was far from being a thorough test.

**Comment by emroussel** [comment]
Oh great, good to know!

**Comment by emroussel** [comment]
After more tests on Android, everything seems to work! The problem was probably associated with Ionic View.
